FROM 303666750405.dkr.ecr.us-west-2.amazonaws.com/risk-prediction/mirai:stable
RUN apt-get update
RUN apt-get install -y zip
RUN apt-get install -y unzip
RUN apt-get install -y tree
RUN apt-get install -y python3-pip 
RUN python3.6 -m pip install --user boto3
COPY *.py . 
COPY dcm_to_png.sh .
COPY risk_factor_pool.py /root/OncoNet/onconet/models/pools/risk_factor_pool.py
COPY resnet_base.py /root/OncoNet/onconet/models/resnet_base.py
COPY custom_resnet.py /root/OncoNet/onconet/models/custom_resnet.py
COPY mirai_full.py /root/OncoNet/onconet/models/mirai_full.py
COPY parsing.py /root/OncoNet/onconet/utils/parsing.py